-- ============================================================
--  Bilwi Cargo & Ride  -  Esquema PostgreSQL
--  Modelo Entidad-Relacion completo para el MVP.
-- ============================================================

-- Limpieza (orden inverso por dependencias)
DROP TABLE IF EXISTS notifications     CASCADE;
DROP TABLE IF EXISTS incidents         CASCADE;
DROP TABLE IF EXISTS messages          CASCADE;
DROP TABLE IF EXISTS ratings           CASCADE;
DROP TABLE IF EXISTS payments          CASCADE;
DROP TABLE IF EXISTS trip_locations    CASCADE;
DROP TABLE IF EXISTS trip_stops        CASCADE;
DROP TABLE IF EXISTS trips             CASCADE;
DROP TABLE IF EXISTS vehicles          CASCADE;
DROP TABLE IF EXISTS driver_documents  CASCADE;
DROP TABLE IF EXISTS drivers           CASCADE;
DROP TABLE IF EXISTS service_types      CASCADE;
DROP TABLE IF EXISTS users             CASCADE;

-- ------------------------------------------------------------
-- USUARIOS (cliente, conductor o admin)
-- ------------------------------------------------------------
CREATE TABLE users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role          TEXT NOT NULL CHECK (role IN ('client','driver','admin')),
  full_name     TEXT NOT NULL,
  phone         TEXT NOT NULL UNIQUE,
  email         TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  photo_url     TEXT,
  status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active','suspended','pending')),
  rating_avg    NUMERIC(3,2) NOT NULL DEFAULT 0,
  rating_count  INTEGER NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
-- CONDUCTORES (extension 1-1 de users)
-- ------------------------------------------------------------
CREATE TABLE drivers (
  user_id          BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  license_number   TEXT,
  license_verified BOOLEAN NOT NULL DEFAULT false,
  id_verified      BOOLEAN NOT NULL DEFAULT false,
  doc_status       TEXT NOT NULL DEFAULT 'pending'
                     CHECK (doc_status IN ('pending','approved','rejected')),
  is_available     BOOLEAN NOT NULL DEFAULT false,
  current_lat      DOUBLE PRECISION,
  current_lng      DOUBLE PRECISION,
  last_location_at TIMESTAMPTZ,
  total_trips      INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_drivers_available ON drivers(is_available);
CREATE INDEX idx_drivers_location  ON drivers(current_lat, current_lng);

-- ------------------------------------------------------------
-- DOCUMENTOS DEL CONDUCTOR (licencia, cedula, circulacion)
-- ------------------------------------------------------------
CREATE TABLE driver_documents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id   BIGINT NOT NULL REFERENCES drivers(user_id) ON DELETE CASCADE,
  type        TEXT NOT NULL CHECK (type IN ('license','id_card','circulation','insurance')),
  url         TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','rejected')),
  reviewed_by BIGINT REFERENCES users(id),
  notes       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_docs_driver ON driver_documents(driver_id);

-- ------------------------------------------------------------
-- VEHICULOS
-- ------------------------------------------------------------
CREATE TABLE vehicles (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id   BIGINT NOT NULL REFERENCES drivers(user_id) ON DELETE CASCADE,
  type        TEXT NOT NULL CHECK (type IN
                ('particular','camioneta','camion_pequeno','camion_mediano','acarreo','moto')),
  brand       TEXT,
  model       TEXT,
  year        INTEGER,
  plate       TEXT,
  color       TEXT,
  capacity_kg INTEGER,
  photo_url   TEXT,
  status      TEXT NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending','approved','rejected')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_vehicles_driver ON vehicles(driver_id);

-- ------------------------------------------------------------
-- TIPOS DE SERVICIO + PARAMETROS DE TARIFA (en cordobas NIO)
-- ------------------------------------------------------------
CREATE TABLE service_types (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code        TEXT NOT NULL UNIQUE,         -- ride, acarreo, comercial
  name        TEXT NOT NULL,
  description TEXT,
  vehicle_type TEXT NOT NULL,               -- tipo de vehiculo sugerido
  base_fare   NUMERIC(10,2) NOT NULL,
  per_km      NUMERIC(10,2) NOT NULL,
  per_min     NUMERIC(10,2) NOT NULL,
  min_fare    NUMERIC(10,2) NOT NULL,
  allows_stops BOOLEAN NOT NULL DEFAULT false,
  active      BOOLEAN NOT NULL DEFAULT true,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ------------------------------------------------------------
-- VIAJES / SOLICITUDES  (carrera, acarreo o comercial)
-- ------------------------------------------------------------
CREATE TABLE trips (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id       BIGINT NOT NULL REFERENCES users(id),
  driver_id       BIGINT REFERENCES users(id),
  vehicle_id      BIGINT REFERENCES vehicles(id),
  service_type_id BIGINT NOT NULL REFERENCES service_types(id),
  status          TEXT NOT NULL DEFAULT 'requested' CHECK (status IN
                    ('requested','accepted','arrived','in_progress','completed','cancelled')),
  -- Origen / destino
  origin_lat      DOUBLE PRECISION NOT NULL,
  origin_lng      DOUBLE PRECISION NOT NULL,
  origin_address  TEXT,
  dest_lat        DOUBLE PRECISION NOT NULL,
  dest_lng        DOUBLE PRECISION NOT NULL,
  dest_address    TEXT,
  -- Metricas
  distance_km     NUMERIC(10,2),
  duration_min    NUMERIC(10,2),
  cargo_size      TEXT CHECK (cargo_size IN ('small','medium','large','xlarge')),
  notes           TEXT,
  -- Tarifa
  fare_estimated  NUMERIC(10,2),
  fare_final      NUMERIC(10,2),
  payment_method  TEXT NOT NULL DEFAULT 'cash'
                    CHECK (payment_method IN ('cash','transfer','mobile','card')),
  cancel_reason   TEXT,
  cancelled_by    BIGINT REFERENCES users(id),
  -- Tiempos del ciclo de vida
  requested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  accepted_at     TIMESTAMPTZ,
  arrived_at      TIMESTAMPTZ,
  started_at      TIMESTAMPTZ,
  completed_at    TIMESTAMPTZ,
  cancelled_at    TIMESTAMPTZ
);
CREATE INDEX idx_trips_client ON trips(client_id);
CREATE INDEX idx_trips_driver ON trips(driver_id);
CREATE INDEX idx_trips_status ON trips(status);

-- Paradas adicionales (acarreo / mudanza)
CREATE TABLE trip_stops (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id   BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  seq       INTEGER NOT NULL,
  lat       DOUBLE PRECISION NOT NULL,
  lng       DOUBLE PRECISION NOT NULL,
  address   TEXT
);
CREATE INDEX idx_stops_trip ON trip_stops(trip_id);

-- Rastro de ubicaciones del conductor durante el viaje (tracking)
CREATE TABLE trip_locations (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id     BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  lat         DOUBLE PRECISION NOT NULL,
  lng         DOUBLE PRECISION NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_triploc_trip ON trip_locations(trip_id);

-- ------------------------------------------------------------
-- PAGOS
-- ------------------------------------------------------------
CREATE TABLE payments (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id    BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  amount     NUMERIC(10,2) NOT NULL,
  commission NUMERIC(10,2) NOT NULL DEFAULT 0,
  method     TEXT NOT NULL CHECK (method IN ('cash','transfer','mobile','card')),
  status     TEXT NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending','paid','failed','refunded')),
  reference  TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_payments_trip ON payments(trip_id);

-- ------------------------------------------------------------
-- CALIFICACIONES (cliente<->conductor)
-- ------------------------------------------------------------
CREATE TABLE ratings (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id    BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  rater_id   BIGINT NOT NULL REFERENCES users(id),
  ratee_id   BIGINT NOT NULL REFERENCES users(id),
  stars      SMALLINT NOT NULL CHECK (stars BETWEEN 1 AND 5),
  comment    TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (trip_id, rater_id)
);
CREATE INDEX idx_ratings_ratee ON ratings(ratee_id);

-- ------------------------------------------------------------
-- CHAT (mensajes por viaje)
-- ------------------------------------------------------------
CREATE TABLE messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id    BIGINT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  sender_id  BIGINT NOT NULL REFERENCES users(id),
  type       TEXT NOT NULL DEFAULT 'text' CHECK (type IN ('text','location','image')),
  body       TEXT,
  lat        DOUBLE PRECISION,
  lng        DOUBLE PRECISION,
  image_url  TEXT,
  read_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_messages_trip ON messages(trip_id);

-- ------------------------------------------------------------
-- INCIDENTES / SOS / REPORTES
-- ------------------------------------------------------------
CREATE TABLE incidents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id     BIGINT REFERENCES trips(id) ON DELETE SET NULL,
  reporter_id BIGINT NOT NULL REFERENCES users(id),
  type        TEXT NOT NULL CHECK (type IN ('sos','accident','harassment','fraud','other')),
  description TEXT,
  lat         DOUBLE PRECISION,
  lng         DOUBLE PRECISION,
  status      TEXT NOT NULL DEFAULT 'open'
                CHECK (status IN ('open','reviewing','resolved')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_incidents_status ON incidents(status);

-- ------------------------------------------------------------
-- NOTIFICACIONES
-- ------------------------------------------------------------
CREATE TABLE notifications (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title      TEXT NOT NULL,
  body       TEXT,
  data       JSONB,
  read_at    TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notif_user ON notifications(user_id);
