-- ============================================================
--  Migracion 001: tabla de uploads + columnas de oferta y precio
--  en vehicles. Idempotente: se puede correr varias veces.
-- ============================================================

CREATE TABLE IF NOT EXISTS uploads (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uploader_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
  mime_type   TEXT NOT NULL,
  data        BYTEA NOT NULL,
  size_bytes  INTEGER NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_uploads_uploader ON uploads(uploader_id);

ALTER TABLE vehicles
  ADD COLUMN IF NOT EXISTS services_offered JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS custom_per_km    NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS custom_base_fare NUMERIC(10,2);
